"""Generates billsmusic/_build_info.py immediately before a Nuitka build,
embedding an immutable record of exactly which commit/tree/build attempt
produced the resulting executable.

Real-device gap (2026-08-31 Codex audit, section 16): the existing
build_identity startup diagnostic (see window.py's _record_build_identity())
only ever reported app_version/build_tag/frozen/executable_basename/size/
mtime -- proof that dist EXE == installed EXE (they can be hashed and
compared byte-for-byte after the fact), but never proof that current
source HEAD -> built EXE, since none of those fields are tied to the
actual git commit/tree the build was compiled from. This script closes
that gap by writing the git commit hash, a dirty-tree flag, the git tree
hash (an existing, already-computed content hash of the whole source
tree at that commit -- no need to hand-roll a second one), a fresh build
UUID, and a UTC build timestamp into a plain Python module that gets
compiled into the frozen build like any other source file. Never run at
normal application startup -- only here, once, immediately before Nuitka
runs (see build_nuitka_installer.bat).
"""
import datetime
import os
import subprocess
import sys
import uuid


def _git(*args):
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=os.path.dirname(os.path.abspath(__file__)),
            text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return None


def main() -> int:
    commit = _git("rev-parse", "HEAD")
    tree_hash = _git("rev-parse", "HEAD^{tree}")
    status = _git("status", "--porcelain")
    dirty = bool(status) if status is not None else None
    build_uuid = str(uuid.uuid4())
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

    content = (
        '"""Auto-generated by generate_build_info.py immediately before '
        'this\nbuild -- DO NOT EDIT BY HAND, and do not trust these values '
        'in a source\ncheckout that has not been through a build (they '
        'stay at the checked-in\nplaceholders until then). See window.py'
        "'s _record_build_identity() and\nCODEX_HANDOFF.md's 2026-08-31 "
        'Codex audit entry ("build identity must become\nimmutable").'
        '"""\n'
        f"BUILD_COMMIT = {commit!r}\n"
        f"BUILD_COMMIT_DIRTY = {dirty!r}\n"
        f"BUILD_TREE_HASH = {tree_hash!r}\n"
        f"BUILD_UUID = {build_uuid!r}\n"
        f"BUILD_TIMESTAMP_UTC = {timestamp!r}\n"
    )
    out_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "billsmusic", "_build_info.py",
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated {out_path}")
    print(f"  commit={commit} dirty={dirty} tree={tree_hash}")
    print(f"  build_uuid={build_uuid} timestamp={timestamp}")
    if commit is None:
        print("WARNING: could not determine git commit -- is this a git checkout?")
    return 0


if __name__ == "__main__":
    sys.exit(main())
