"""Auto-generated by generate_build_info.py immediately before this
build -- DO NOT EDIT BY HAND, and do not trust these values in a source
checkout that has not been through a build (they stay at the checked-in
placeholders until then). See window.py's _record_build_identity() and
CODEX_HANDOFF.md's 2026-08-31 Codex audit entry ("build identity must become
immutable")."""
BUILD_COMMIT = 'ceb42b0e4263c9ca1c5f8f73d25d32bcd5ea525a'
BUILD_COMMIT_DIRTY = False
BUILD_TREE_HASH = '113c91400107b8a073b1bce6d28a19a395613090'
BUILD_UUID = 'f3aa97d0-1959-42dc-ba9c-05f5134662d5'
BUILD_TIMESTAMP_UTC = '2026-09-13T13:26:10.442116+00:00'
